export const TIMEZONES = {
  "UTC": [
    { value: "UTC", label: "UTC — UTC+0" }
  ],
  "Africa": [
    { value: "Africa/Abidjan", label: "Abidjan — UTC+0" },
    { value: "Africa/Accra", label: "Accra — UTC+0" },
    { value: "Africa/Addis_Ababa", label: "Addis Ababa — UTC+3" },
    { value: "Africa/Algiers", label: "Algiers — UTC+1" },
    { value: "Africa/Cairo", label: "Cairo — UTC+2" },
    { value: "Africa/Casablanca", label: "Casablanca — UTC+1" },
    { value: "Africa/Johannesburg", label: "Johannesburg — UTC+2" },
    { value: "Africa/Lagos", label: "Lagos — UTC+1" },
    { value: "Africa/Nairobi", label: "Nairobi — UTC+3" },
    { value: "Africa/Tripoli", label: "Tripoli — UTC+2" },
    { value: "Africa/Tunis", label: "Tunis — UTC+1" }
  ],
  "Americas": [
    { value: "America/Adak", label: "Adak — UTC-10/UTC-9" },
    { value: "America/Anchorage", label: "Anchorage — UTC-9/UTC-8" },
    { value: "America/Argentina/Buenos_Aires", label: "Buenos Aires — UTC-3" },
    { value: "America/Bogota", label: "Bogota — UTC-5" },
    { value: "America/Caracas", label: "Caracas — UTC-4" },
    { value: "America/Chicago", label: "Chicago (CST/CDT) — UTC-6/UTC-5" },
    { value: "America/Costa_Rica", label: "Costa Rica — UTC-6" },
    { value: "America/Denver", label: "Denver (MST/MDT) — UTC-7/UTC-6" },
    { value: "America/Edmonton", label: "Edmonton — UTC-7/UTC-6" },
    { value: "America/El_Salvador", label: "El Salvador — UTC-6" },
    { value: "America/Guatemala", label: "Guatemala — UTC-6" },
    { value: "America/Guayaquil", label: "Guayaquil — UTC-5" },
    { value: "America/Halifax", label: "Halifax — UTC-4/UTC-3" },
    { value: "America/Havana", label: "Havana — UTC-5/UTC-4" },
    { value: "America/Lima", label: "Lima — UTC-5" },
    { value: "America/Los_Angeles", label: "Los Angeles (PST/PDT) — UTC-8/UTC-7" },
    { value: "America/Managua", label: "Managua — UTC-6" },
    { value: "America/Mexico_City", label: "Mexico City — UTC-6/UTC-5" },
    { value: "America/Montevideo", label: "Montevideo — UTC-3" },
    { value: "America/New_York", label: "New York (EST/EDT) — UTC-5/UTC-4" },
    { value: "America/Noronha", label: "Noronha — UTC-2" },
    { value: "America/Panama", label: "Panama — UTC-5" },
    { value: "America/Phoenix", label: "Phoenix (MST) — UTC-7" },
    { value: "America/Puerto_Rico", label: "Puerto Rico — UTC-4" },
    { value: "America/Regina", label: "Regina (CST) — UTC-6" },
    { value: "America/Santiago", label: "Santiago — UTC-4/UTC-3" },
    { value: "America/Santo_Domingo", label: "Santo Domingo — UTC-4" },
    { value: "America/Sao_Paulo", label: "São Paulo — UTC-3" },
    { value: "America/St_Johns", label: "St. Johns — UTC-3:30/UTC-2:30" },
    { value: "America/Tegucigalpa", label: "Tegucigalpa — UTC-6" },
    { value: "America/Tijuana", label: "Tijuana — UTC-8/UTC-7" },
    { value: "America/Toronto", label: "Toronto — UTC-5/UTC-4" },
    { value: "America/Vancouver", label: "Vancouver — UTC-8/UTC-7" },
    { value: "America/Winnipeg", label: "Winnipeg — UTC-6/UTC-5" }
  ],
  "Antarctica": [
    { value: "Antarctica/Casey", label: "Casey — UTC+11" },
    { value: "Antarctica/Davis", label: "Davis — UTC+7" },
    { value: "Antarctica/McMurdo", label: "McMurdo — UTC+13/UTC+12" },
    { value: "Antarctica/Palmer", label: "Palmer — UTC-3" },
    { value: "Antarctica/Rothera", label: "Rothera — UTC-3" },
    { value: "Antarctica/Troll", label: "Troll — UTC+2/UTC+0" }
  ],
  "Asia": [
    { value: "Asia/Almaty", label: "Almaty — UTC+6" },
    { value: "Asia/Amman", label: "Amman — UTC+3" },
    { value: "Asia/Anadyr", label: "Anadyr — UTC+12" },
    { value: "Asia/Ashgabat", label: "Ashgabat — UTC+5" },
    { value: "Asia/Baghdad", label: "Baghdad — UTC+3" },
    { value: "Asia/Bahrain", label: "Bahrain — UTC+3" },
    { value: "Asia/Baku", label: "Baku — UTC+4" },
    { value: "Asia/Bangkok", label: "Bangkok — UTC+7" },
    { value: "Asia/Beirut", label: "Beirut — UTC+3/UTC+2" },
    { value: "Asia/Bishkek", label: "Bishkek — UTC+6" },
    { value: "Asia/Brunei", label: "Brunei — UTC+8" },
    { value: "Asia/Calcutta", label: "Kolkata / Mumbai (IST) — UTC+5:30" },
    { value: "Asia/Colombo", label: "Colombo — UTC+5:30" },
    { value: "Asia/Damascus", label: "Damascus — UTC+3/UTC+2" },
    { value: "Asia/Dhaka", label: "Dhaka — UTC+6" },
    { value: "Asia/Dubai", label: "Dubai (GST) — UTC+4" },
    { value: "Asia/Dushanbe", label: "Dushanbe — UTC+5" },
    { value: "Asia/Gaza", label: "Gaza — UTC+3/UTC+2" },
    { value: "Asia/Hong_Kong", label: "Hong Kong — UTC+8" },
    { value: "Asia/Ho_Chi_Minh", label: "Ho Chi Minh — UTC+7" },
    { value: "Asia/Irkutsk", label: "Irkutsk — UTC+8" },
    { value: "Asia/Jakarta", label: "Jakarta — UTC+7" },
    { value: "Asia/Jerusalem", label: "Jerusalem — UTC+3/UTC+2" },
    { value: "Asia/Kabul", label: "Kabul — UTC+4:30" },
    { value: "Asia/Kamchatka", label: "Kamchatka — UTC+12" },
    { value: "Asia/Karachi", label: "Karachi (PKT) — UTC+5" },
    { value: "Asia/Kathmandu", label: "Kathmandu — UTC+5:45" },
    { value: "Asia/Krasnoyarsk", label: "Krasnoyarsk — UTC+7" },
    { value: "Asia/Kuala_Lumpur", label: "Kuala Lumpur — UTC+8" },
    { value: "Asia/Kuwait", label: "Kuwait — UTC+3" },
    { value: "Asia/Macau", label: "Macau — UTC+8" },
    { value: "Asia/Magadan", label: "Magadan — UTC+11" },
    { value: "Asia/Manila", label: "Manila — UTC+8" },
    { value: "Asia/Muscat", label: "Muscat — UTC+4" },
    { value: "Asia/Nicosia", label: "Nicosia — UTC+3/UTC+2" },
    { value: "Asia/Novosibirsk", label: "Novosibirsk — UTC+7" },
    { value: "Asia/Omsk", label: "Omsk — UTC+6" },
    { value: "Asia/Oral", label: "Oral — UTC+5" },
    { value: "Asia/Phnom_Penh", label: "Phnom Penh — UTC+7" },
    { value: "Asia/Pyongyang", label: "Pyongyang — UTC+9" },
    { value: "Asia/Qatar", label: "Qatar — UTC+3" },
    { value: "Asia/Rangoon", label: "Yangon — UTC+6:30" },
    { value: "Asia/Riyadh", label: "Riyadh — UTC+3" },
    { value: "Asia/Sakhalin", label: "Sakhalin — UTC+11" },
    { value: "Asia/Samarkand", label: "Samarkand — UTC+5" },
    { value: "Asia/Seoul", label: "Seoul — UTC+9" },
    { value: "Asia/Shanghai", label: "Shanghai — UTC+8" },
    { value: "Asia/Singapore", label: "Singapore — UTC+8" },
    { value: "Asia/Taipei", label: "Taipei — UTC+8" },
    { value: "Asia/Tashkent", label: "Tashkent — UTC+5" },
    { value: "Asia/Tbilisi", label: "Tbilisi — UTC+4" },
    { value: "Asia/Tehran", label: "Tehran — UTC+3:30/UTC+4:30" },
    { value: "Asia/Thimphu", label: "Thimphu — UTC+6" },
    { value: "Asia/Tokyo", label: "Tokyo (JST) — UTC+9" },
    { value: "Asia/Ulaanbaatar", label: "Ulaanbaatar — UTC+8" },
    { value: "Asia/Urumqi", label: "Urumqi — UTC+6" },
    { value: "Asia/Vladivostok", label: "Vladivostok — UTC+10" },
    { value: "Asia/Yakutsk", label: "Yakutsk — UTC+9" },
    { value: "Asia/Yekaterinburg", label: "Yekaterinburg — UTC+5" },
    { value: "Asia/Yerevan", label: "Yerevan — UTC+4" }
  ],
  "Europe": [
    { value: "Europe/Amsterdam", label: "Amsterdam — UTC+2/UTC+1" },
    { value: "Europe/Andorra", label: "Andorra — UTC+2/UTC+1" },
    { value: "Europe/Athens", label: "Athens — UTC+3/UTC+2" },
    { value: "Europe/Belgrade", label: "Belgrade — UTC+2/UTC+1" },
    { value: "Europe/Berlin", label: "Berlin — UTC+2/UTC+1" },
    { value: "Europe/Brussels", label: "Brussels — UTC+2/UTC+1" },
    { value: "Europe/Bucharest", label: "Bucharest — UTC+3/UTC+2" },
    { value: "Europe/Budapest", label: "Budapest — UTC+2/UTC+1" },
    { value: "Europe/Chisinau", label: "Chisinau — UTC+3/UTC+2" },
    { value: "Europe/Copenhagen", label: "Copenhagen — UTC+2/UTC+1" },
    { value: "Europe/Dublin", label: "Dublin — UTC+1/UTC+0" },
    { value: "Europe/Gibraltar", label: "Gibraltar — UTC+2/UTC+1" },
    { value: "Europe/Helsinki", label: "Helsinki — UTC+3/UTC+2" },
    { value: "Europe/Istanbul", label: "Istanbul — UTC+3" },
    { value: "Europe/Kaliningrad", label: "Kaliningrad — UTC+2" },
    { value: "Europe/Kiev", label: "Kyiv — UTC+3/UTC+2" },
    { value: "Europe/Lisbon", label: "Lisbon — UTC+1/UTC+0" },
    { value: "Europe/London", label: "London (GMT/BST) — UTC+1/UTC+0" },
    { value: "Europe/Luxembourg", label: "Luxembourg — UTC+2/UTC+1" },
    { value: "Europe/Madrid", label: "Madrid — UTC+2/UTC+1" },
    { value: "Europe/Malta", label: "Malta — UTC+2/UTC+1" },
    { value: "Europe/Minsk", label: "Minsk — UTC+3" },
    { value: "Europe/Monaco", label: "Monaco — UTC+2/UTC+1" },
    { value: "Europe/Moscow", label: "Moscow — UTC+3" },
    { value: "Europe/Nicosia", label: "Nicosia — UTC+3/UTC+2" },
    { value: "Europe/Oslo", label: "Oslo — UTC+2/UTC+1" },
    { value: "Europe/Paris", label: "Paris (CET/CEST) — UTC+2/UTC+1" },
    { value: "Europe/Prague", label: "Prague — UTC+2/UTC+1" },
    { value: "Europe/Riga", label: "Riga — UTC+3/UTC+2" },
    { value: "Europe/Rome", label: "Rome — UTC+2/UTC+1" },
    { value: "Europe/Samara", label: "Samara — UTC+4" },
    { value: "Europe/Sarajevo", label: "Sarajevo — UTC+2/UTC+1" },
    { value: "Europe/Simferopol", label: "Simferopol — UTC+3" },
    { value: "Europe/Sofia", label: "Sofia — UTC+3/UTC+2" }
  ],
  "Indian Ocean": [
    { value: "Indian/Chagos", label: "Chagos — UTC+6" },
    { value: "Indian/Christmas", label: "Christmas Island — UTC+7" },
    { value: "Indian/Cocos", label: "Cocos Islands — UTC+6:30" },
    { value: "Indian/Kerguelen", label: "Kerguelen — UTC+5" },
    { value: "Indian/Mahe", label: "Mahe — UTC+4" },
    { value: "Indian/Maldives", label: "Maldives — UTC+5" },
    { value: "Indian/Mauritius", label: "Mauritius — UTC+4" },
    { value: "Indian/Reunion", label: "Reunion — UTC+4" }
  ],
  "Pacific": [
    { value: "Pacific/Apia", label: "Apia — UTC+13" },
    { value: "Pacific/Auckland", label: "Auckland — UTC+13/UTC+12" },
    { value: "Pacific/Chatham", label: "Chatham — UTC+13:45/UTC+12:45" },
    { value: "Pacific/Easter", label: "Easter Island — UTC-5/UTC-6" },
    { value: "Pacific/Efate", label: "Efate — UTC+11" },
    { value: "Pacific/Enderbury", label: "Enderbury — UTC+13" },
    { value: "Pacific/Fakaofo", label: "Fakaofo — UTC+13" },
    { value: "Pacific/Fiji", label: "Fiji — UTC+12" },
    { value: "Pacific/Funafuti", label: "Funafuti — UTC+12" },
    { value: "Pacific/Galapagos", label: "Galapagos — UTC-6" },
    { value: "Pacific/Gambier", label: "Gambier — UTC-9" },
    { value: "Pacific/Guadalcanal", label: "Guadalcanal — UTC+11" },
    { value: "Pacific/Guam", label: "Guam — UTC+10" },
    { value: "Pacific/Honolulu", label: "Honolulu (HST) — UTC-10" },
    { value: "Pacific/Kiritimati", label: "Kiritimati — UTC+14" },
    { value: "Pacific/Kosrae", label: "Kosrae — UTC+11" },
    { value: "Pacific/Kwajalein", label: "Kwajalein — UTC+12" },
    { value: "Pacific/Majuro", label: "Majuro — UTC+12" },
    { value: "Pacific/Marquesas", label: "Marquesas — UTC-9:30" },
    { value: "Pacific/Nauru", label: "Nauru — UTC+12" },
    { value: "Pacific/Niue", label: "Niue — UTC-11" },
    { value: "Pacific/Norfolk", label: "Norfolk — UTC+12/UTC+11" },
    { value: "Pacific/Noumea", label: "Noumea — UTC+11" },
    { value: "Pacific/Pago_Pago", label: "Pago Pago — UTC-11" },
    { value: "Pacific/Palau", label: "Palau — UTC+9" },
    { value: "Pacific/Pitcairn", label: "Pitcairn — UTC-8" },
    { value: "Pacific/Pohnpei", label: "Pohnpei — UTC+11" },
    { value: "Pacific/Port_Moresby", label: "Port Moresby — UTC+10" },
    { value: "Pacific/Rarotonga", label: "Rarotonga — UTC-10" },
    { value: "Pacific/Tahiti", label: "Tahiti — UTC-10" },
    { value: "Pacific/Tarawa", label: "Tarawa — UTC+12" },
    { value: "Pacific/Tongatapu", label: "Tongatapu — UTC+13" },
    { value: "Pacific/Wake", label: "Wake — UTC+12" },
    { value: "Pacific/Wallis", label: "Wallis — UTC+12" }
  ]
};
